# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5474a0d0d1d5da45ef90096023d1a0579687a248162fa70c129695ecfb166d2eb7944f7ae063c4ca31589980ad1a36914c2e6078bf3eabf9ac6aad21860bc91

test:
  secret_key_base: 0e75a30120d96e03b4757ae22893deff8e965b75276bcda5db05bbd00c93c2bab1439465e5d641f4c700a9f43c7b7c116df6539bdbb932adcad6d3d280c6f6a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
